version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /dev:/dev
      - ./data:/app/data
    privileged: true
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - ALLOW_ORIGINS=http://localhost:3000
    restart: unless-stopped
